In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [50]:
application_test = pd.read_csv("home-credit-default-risk/application_test.csv")
application_train = pd.read_csv("home-credit-default-risk/application_train.csv")
bureau = pd.read_csv("home-credit-default-risk/bureau.csv")
bureau_balance = pd.read_csv("home-credit-default-risk/bureau_balance.csv")
credit_card_balance = pd.read_csv("home-credit-default-risk/credit_card_balance.csv")
installments_payments = pd.read_csv("home-credit-default-risk/installments_payments.csv")
POS_CASH_balance = pd.read_csv("home-credit-default-risk/POS_CASH_balance.csv")
previous_application = pd.read_csv("home-credit-default-risk/previous_application.csv")
sample_submission = pd.read_csv("home-credit-default-risk/sample_submission.csv")

In [51]:
application_train.shape

(307511, 122)

In [52]:
#bureau.csv

In [53]:
bureau.shape

(1716428, 17)

In [54]:
bureau.columns

Index(['SK_ID_CURR', 'SK_ID_BUREAU', 'CREDIT_ACTIVE', 'CREDIT_CURRENCY',
       'DAYS_CREDIT', 'CREDIT_DAY_OVERDUE', 'DAYS_CREDIT_ENDDATE',
       'DAYS_ENDDATE_FACT', 'AMT_CREDIT_MAX_OVERDUE', 'CNT_CREDIT_PROLONG',
       'AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT', 'AMT_CREDIT_SUM_LIMIT',
       'AMT_CREDIT_SUM_OVERDUE', 'CREDIT_TYPE', 'DAYS_CREDIT_UPDATE',
       'AMT_ANNUITY'],
      dtype='object')

In [55]:
bureau["SK_ID_CURR"].nunique()

305811

In [56]:
bureau.head(15)

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,0.00,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.00,171342.00,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.50,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.00,NaN,NaN,0.0,Consumer credit,-21,NaN
5,215354,5714467,Active,currency 1,-273,0,27460.0,NaN,0.0,0,180000.00,71017.38,108982.62,0.0,Credit card,-31,NaN
6,215354,5714468,Active,currency 1,-43,0,79.0,NaN,0.0,0,42103.80,42103.80,0.00,0.0,Consumer credit,-22,NaN
7,162297,5714469,Closed,currency 1,-1896,0,-1684.0,-1710.0,14985.0,0,76878.45,0.00,0.00,0.0,Consumer credit,-1710,NaN
8,162297,5714470,Closed,currency 1,-1146,0,-811.0,-840.0,0.0,0,103007.70,0.00,0.00,0.0,Consumer credit,-840,NaN
9,162297,5714471,Active,currency 1,-1146,0,-484.0,NaN,0.0,0,4500.00,0.00,0.00,0.0,Credit card,-690,NaN
10,162297,5714472,Active,currency 1,-1146,0,-180.0,NaN,0.0,0,337500.00,0.00,0.00,0.0,Credit card,-690,NaN
11,162297,5714473,Closed,currency 1,-2456,0,-629.0,-825.0,NaN,0,675000.00,0.00,0.00,0.0,Consumer credit,-706,NaN
12,162297,5714474,Active,currency 1,-277,0,5261.0,NaN,0.0,0,7033500.00,NaN,NaN,0.0,Mortgage,-31,NaN
13,402440,5714475,Active,currency 1,-96,0,269.0,NaN,0.0,0,89910.00,76905.00,0.00,0.0,Consumer credit,-22,NaN
14,238881,5714482,Closed,currency 1,-318,0,-187.0,-187.0,NaN,0,0.00,0.00,0.00,0.0,Credit card,-185,NaN

In [57]:
bureau["CREDIT_ACTIVE"].value_counts()

CREDIT_ACTIVE
Closed      1079273
Active       630607
Sold           6527
Bad debt         21
Name: count, dtype: int64

In [58]:
bureau.isnull().sum().sort_values(ascending=False)

AMT_ANNUITY               1226791
AMT_CREDIT_MAX_OVERDUE    1124488
DAYS_ENDDATE_FACT          633653
AMT_CREDIT_SUM_LIMIT       591780
AMT_CREDIT_SUM_DEBT        257669
DAYS_CREDIT_ENDDATE        105553
AMT_CREDIT_SUM                 13
CREDIT_ACTIVE                   0
CREDIT_CURRENCY                 0
DAYS_CREDIT                     0
CREDIT_DAY_OVERDUE              0
SK_ID_BUREAU                    0
CNT_CREDIT_PROLONG              0
AMT_CREDIT_SUM_OVERDUE          0
CREDIT_TYPE                     0
DAYS_CREDIT_UPDATE              0
SK_ID_CURR                      0
dtype: int64

In [59]:
#AMT_ANNUITY und AMT_CREDIT_MAX_OVERDUE haben mehr als 50% NA Werte
bureau.drop(columns=['AMT_ANNUITY', "AMT_CREDIT_MAX_OVERDUE"], inplace=True)

In [60]:
#AMT_CREDIT_SUM hat nur 13 NA Werte. Diese Zeilen droppen wir einfach
bureau = bureau.dropna(subset=["AMT_CREDIT_SUM"])

In [61]:
bureau["CREDIT_ACTIVE"].value_counts()

CREDIT_ACTIVE
Closed      1079268
Active       630599
Sold           6527
Bad debt         21
Name: count, dtype: int64

In [62]:
#bureau_balance

In [63]:
bureau_balance.shape

(27299925, 3)

In [64]:
bureau_balance.columns

Index(['SK_ID_BUREAU', 'MONTHS_BALANCE', 'STATUS'], dtype='object')

In [65]:
bureau_balance.describe()

       SK_ID_BUREAU  MONTHS_BALANCE
count  2.729992e+07    2.729992e+07
mean   6.036297e+06   -3.074169e+01
std    4.923489e+05    2.386451e+01
min    5.001709e+06   -9.600000e+01
25%    5.730933e+06   -4.600000e+01
50%    6.070821e+06   -2.500000e+01
75%    6.431951e+06   -1.100000e+01
max    6.842888e+06    0.000000e+00

In [66]:
bureau_balance["STATUS"].value_counts()

STATUS
C    13646993
0     7499507
X     5810482
1      242347
5       62406
2       23419
3        8924
4        5847
Name: count, dtype: int64

In [67]:
bureau_balance.isnull().sum().sort_values(ascending=False)

SK_ID_BUREAU      0
MONTHS_BALANCE    0
STATUS            0
dtype: int64

In [68]:
#Aggregation bureau_balance mit bureau

In [69]:
bureau_balance_agg = bureau_balance.groupby("SK_ID_BUREAU").agg(
    bb_months_count=("MONTHS_BALANCE", "count"),      # wie viele Monate Daten vorhanden
    bb_max_dpd=("STATUS", lambda x: x[x.isin(["1","2","3","4","5"])].astype(float).max()),  # schlimmster DPD Status
    bb_bad_months=("STATUS", lambda x: x.isin(["4","5"]).sum()),  # Monate mit ernstem Verzug
).reset_index()

bureau = bureau.merge(bureau_balance_agg, on="SK_ID_BUREAU", how="left")

In [70]:
bureau.describe()

,SK_ID_CURR,SK_ID_BUREAU,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,DAYS_CREDIT_UPDATE,bb_months_count,bb_max_dpd,bb_bad_months
count,1.716415e+06,1.716415e+06,1.716415e+06,1.716415e+06,1.610871e+06,1.082770e+06,1.716415e+06,1.716415e+06,1.458746e+06,1.124648e+06,1.716415e+06,1.716415e+06,774349.000000,98651.000000,774349.000000
mean,2.782147e+05,5.924434e+06,-1.142115e+03,8.181728e-01,5.105173e+02,-1.017441e+03,6.410454e-03,3.549946e+05,1.370825e+05,6.229515e+03,3.791304e+01,-5.937526e+02,31.225889,1.321629,0.071518
std,1.029384e+05,5.322663e+05,7.951627e+02,3.654457e+01,4.994226e+03,7.140102e+02,9.622427e-02,1.149811e+06,6.774004e+05,4.503203e+04,5.937673e+03,7.207484e+02,23.483787,0.924993,1.397812
min,1.000010e+05,5.000000e+06,-2.922000e+03,0.000000e+00,-4.206000e+04,-4.202300e+04,0.000000e+00,0.000000e+00,-4.705600e+06,-5.864061e+05,0.000000e+00,-4.194700e+04,1.000000,1.000000,0.000000
25%,1.888665e+05,5.463952e+06,-1.666000e+03,0.000000e+00,-1.138000e+03,-1.489000e+03,0.000000e+00,5.130000e+04,0.000000e+00,0.000000e+00,0.000000e+00,-9.080000e+02,12.000000,1.000000,0.000000
50%,2.780550e+05,5.926301e+06,-9.870000e+02,0.000000e+00,-3.300000e+02,-8.970000e+02,0.000000e+00,1.255185e+05,0.000000e+00,0.000000e+00,0.000000e+00,-3.950000e+02,25.000000,1.000000,0.000000
75%,3.674250e+05,6.385682e+06,-4.740000e+02,0.000000e+00,4.740000e+02,-4.250000e+02,0.000000e+00,3.150000e+05,4.015350e+04,0.000000e+00,0.000000e+00,-3.300000e+01,45.000000,1.000000,0.000000
max,4.562550e+05,6.843457e+06,0.000000e+00,2.792000e+03,3.119900e+04,0.000000e+00,9.000000e+00,5.850000e+08,1.701000e+08,4.705600e+06,3.756681e+06,3.720000e+02,97.000000,5.000000,89.000000

In [71]:
bureau_agg = bureau.groupby("SK_ID_CURR").agg(
    bureau_loan_count=("SK_ID_BUREAU", "count"),    #Anzahl Kredite
    bureau_active_count=("CREDIT_ACTIVE", lambda x: (x == "Active").sum()), #Anzahl Aktive Kredite
    bureau_total_credit=("AMT_CREDIT_SUM", "sum"),  #Gesamtkreditehöhe
    bureau_total_debt=("AMT_CREDIT_SUM_DEBT", "sum"),   #Gesamtschulden
    bureau_current_debt=("AMT_CREDIT_SUM_OVERDUE", "sum"),  #Aktuelle Schulden

    bureau_avg_credit_age=("DAYS_CREDIT", "mean"),       # wie lange zurück die Kredite sind
    bureau_most_recent_credit=("DAYS_CREDIT", "max"),    # jüngster Kredit
    bureau_oldest_credit=("DAYS_CREDIT", "min"),         # ältester Kredit

    bureau_avg_credit=("AMT_CREDIT_SUM", "mean"),
    bureau_max_credit=("AMT_CREDIT_SUM", "max"),

    bb_months_count = ("bb_months_count", "sum"),
    bb_max_dpd=("bb_max_dpd", "max"),
    bb_bad_months=("bb_bad_months", "sum"),
).reset_index()

print(application_train.shape)
application_train = application_train.merge(bureau_agg, on="SK_ID_CURR", how="left")

(307511, 122)

In [72]:
print(bureau_agg.shape)

(305809, 14)

In [87]:
application_train.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,cc_prev_loans,cc_avg_payment,cc_total_payment,cc_avg_balance,cc_max_balance,cc_avg_utilization,cc_max_utilization,cc_installments_mature,cc_max_dpd,cc_bad_months
count,307511.000000,307511.000000,307511.000000,3.075110e+05,3.075110e+05,307499.000000,3.072330e+05,307511.000000,307511.000000,252137.000000,...,86905.000000,8.690500e+04,8.690500e+04,86905.000000,8.690500e+04,86905.000000,8.690500e+04,86905.000000,86905.000000,86905.000000
mean,278180.518577,0.080729,0.417052,1.687979e+05,5.990260e+05,27108.573909,5.383962e+05,0.020868,-16036.995067,-2384.169325,...,1.006294,1.042754e+04,2.835346e+05,71459.926952,1.445013e+05,13.942605,5.408275e+01,16.287555,0.780024,0.901456
std,102790.175348,0.272419,0.722121,2.371231e+05,4.024908e+05,14493.737315,3.694465e+05,0.013831,4363.988632,2338.360162,...,0.079955,2.175598e+04,4.509276e+05,109056.518226,1.728090e+05,1540.163308,5.833504e+03,21.651411,23.814510,3.380000
min,100002.000000,0.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,4.050000e+04,0.000290,-25229.000000,-17912.000000,...,1.000000,0.000000e+00,0.000000e+00,-2930.232558,0.000000e+00,-36.990852,0.000000e+00,0.000000,0.000000,0.000000
25%,189145.500000,0.000000,0.000000,1.125000e+05,2.700000e+05,16524.000000,2.385000e+05,0.010006,-19682.000000,-3175.000000,...,1.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000
50%,278202.000000,0.000000,0.000000,1.471500e+05,5.135310e+05,24903.000000,4.500000e+05,0.018850,-15750.000000,-1648.000000,...,1.000000,4.093972e+03,1.235768e+05,26793.606316,9.742432e+04,0.191731,9.504204e-01,8.000000,0.000000,0.000000
75%,367142.500000,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12413.000000,-767.000000,...,1.000000,1.200303e+04,3.991500e+05,98610.502500,1.951825e+05,0.558509,1.045261e+00,23.000000,0.000000,0.000000
max,456255.000000,1.000000,19.000000,1.170000e+08,4.050000e+06,258025.500000,4.050000e+06,0.072508,-7489.000000,0.000000,...,4.000000,1.125000e+06,1.921012e+07,928686.323571,1.354829e+06,380993.152500,1.139278e+06,120.000000,2800.000000,94.000000

In [74]:
#bei diesen Spalten können wir die NA Werte getrost durch 0 ersetzen
bureau_cols = ["bureau_loan_count", "bureau_active_count", "bureau_total_credit",
               "bureau_total_debt", "bureau_current_debt", "bureau_avg_credit",
               "bureau_max_credit"]

application_train[bureau_cols] = application_train[bureau_cols].fillna(0)

In [75]:
#es gab eine Fehlerhafte Zeile wo jemand seit 1000 Jahren angestellt war
application_train['DAYS_EMPLOYED'].replace(365243, np.nan, inplace=True)

In [ ]:
#credit card balance

In [76]:
credit_card_balance.shape

(3840312, 23)

In [77]:
credit_card_balance.head(15)

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.500,0.0,877.500,1700.325,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.000,0.0,0.000,2250.000,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.000,0.0,0.000,2250.000,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.000,0.0,0.000,11795.760,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.000,0.0,11547.000,22924.890,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0
5,2646502,380010,-7,82903.815,270000,0.0,0.000,0.0,0.000,4449.105,...,82773.315,82773.315,0.0,0,0.0,0.0,2.0,Active,7,0
6,1079071,171320,-6,353451.645,585000,67500.0,67500.000,0.0,0.000,14684.175,...,351881.145,351881.145,1.0,1,0.0,0.0,6.0,Active,0,0
7,2095912,118650,-7,47962.125,45000,45000.0,45000.000,0.0,0.000,0.000,...,47962.125,47962.125,1.0,1,0.0,0.0,51.0,Active,0,0
8,2181852,367360,-4,291543.075,292500,90000.0,289339.425,0.0,199339.425,130.500,...,286831.575,286831.575,3.0,8,0.0,5.0,3.0,Active,0,0
9,1235299,203885,-5,201261.195,225000,76500.0,111026.700,0.0,34526.700,6338.340,...,197224.695,197224.695,3.0,9,0.0,6.0,38.0,Active,0,0
10,1108284,209660,-7,102076.560,180000,92250.0,92250.000,0.0,0.000,0.000,...,94224.060,94224.060,5.0,5,0.0,0.0,0.0,Active,0,0
11,2740914,340339,-1,131669.145,225000,10800.0,10800.000,0.0,0.000,6000.480,...,127891.935,127891.935,2.0,2,0.0,0.0,6.0,Active,0,0
12,1985699,302517,-4,1427.265,135000,4500.0,101304.720,0.0,96804.720,3023.955,...,0.000,0.000,1.0,30,0.0,29.0,27.0,Active,0,0
13,1441883,171537,-5,0.000,270000,0.0,0.000,0.0,0.000,12218.490,...,0.000,0.000,0.0,0,0.0,0.0,2.0,Active,0,0
14,1864742,303581,-1,0.000,45000,0.0,0.000,0.0,0.000,0.000,...,0.000,0.000,0.0,0,0.0,0.0,59.0,Active,0,0

In [78]:
credit_card_balance.columns

Index(['SK_ID_PREV', 'SK_ID_CURR', 'MONTHS_BALANCE', 'AMT_BALANCE',
       'AMT_CREDIT_LIMIT_ACTUAL', 'AMT_DRAWINGS_ATM_CURRENT',
       'AMT_DRAWINGS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT',
       'AMT_DRAWINGS_POS_CURRENT', 'AMT_INST_MIN_REGULARITY',
       'AMT_PAYMENT_CURRENT', 'AMT_PAYMENT_TOTAL_CURRENT',
       'AMT_RECEIVABLE_PRINCIPAL', 'AMT_RECIVABLE', 'AMT_TOTAL_RECEIVABLE',
       'CNT_DRAWINGS_ATM_CURRENT', 'CNT_DRAWINGS_CURRENT',
       'CNT_DRAWINGS_OTHER_CURRENT', 'CNT_DRAWINGS_POS_CURRENT',
       'CNT_INSTALMENT_MATURE_CUM', 'NAME_CONTRACT_STATUS', 'SK_DPD',
       'SK_DPD_DEF'],
      dtype='object')

In [84]:
credit_card_balance.describe()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,SK_DPD,SK_DPD_DEF,utilization_rate
count,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.090496e+06,3.840312e+06,3.090496e+06,3.090496e+06,3.535076e+06,...,3.840312e+06,3.840312e+06,3.090496e+06,3.840312e+06,3.090496e+06,3.090496e+06,3.535076e+06,3.840312e+06,3.840312e+06,3.840312e+06
mean,1.904504e+06,2.783242e+05,-3.452192e+01,5.830016e+04,1.538080e+05,5.961325e+03,7.433388e+03,2.881696e+02,2.968805e+03,3.540204e+03,...,5.808881e+04,5.809829e+04,3.094490e-01,7.031439e-01,4.812496e-03,5.594791e-01,2.082508e+01,9.283667e+00,3.316220e-01,5.097742e+00
std,5.364695e+05,1.027045e+05,2.666775e+01,1.063070e+05,1.651457e+05,2.822569e+04,3.384608e+04,8.201989e+03,2.079689e+04,5.600154e+03,...,1.059654e+05,1.059718e+05,1.100401e+00,3.190347e+00,8.263861e-02,3.240649e+00,2.005149e+01,9.751570e+01,2.147923e+01,1.141341e+03
min,1.000018e+06,1.000060e+05,-9.600000e+01,-4.202502e+05,0.000000e+00,-6.827310e+03,-6.211620e+03,0.000000e+00,0.000000e+00,0.000000e+00,...,-4.202502e+05,-4.202502e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-5.069700e+02
25%,1.434385e+06,1.895170e+05,-5.500000e+01,0.000000e+00,4.500000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.897122e+06,2.783960e+05,-2.800000e+01,0.000000e+00,1.125000e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+01,0.000000e+00,0.000000e+00,0.000000e+00
75%,2.369328e+06,3.675800e+05,-1.100000e+01,8.904669e+04,1.800000e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.633911e+03,...,8.889949e+04,8.891451e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.200000e+01,0.000000e+00,0.000000e+00,7.528535e-01
max,2.843496e+06,4.562500e+05,-1.000000e+00,1.505902e+06,1.350000e+06,2.115000e+06,2.287098e+06,1.529847e+06,2.239274e+06,2.028820e+05,...,1.493338e+06,1.493338e+06,5.100000e+01,1.650000e+02,1.200000e+01,1.650000e+02,1.200000e+02,3.260000e+03,3.260000e+03,1.139278e+06

In [81]:
credit_card_balance.isnull().sum().sort_values(ascending=False)

AMT_PAYMENT_CURRENT           767988
AMT_DRAWINGS_ATM_CURRENT      749816
CNT_DRAWINGS_POS_CURRENT      749816
AMT_DRAWINGS_OTHER_CURRENT    749816
AMT_DRAWINGS_POS_CURRENT      749816
CNT_DRAWINGS_OTHER_CURRENT    749816
CNT_DRAWINGS_ATM_CURRENT      749816
CNT_INSTALMENT_MATURE_CUM     305236
AMT_INST_MIN_REGULARITY       305236
SK_ID_PREV                         0
AMT_TOTAL_RECEIVABLE               0
SK_DPD                             0
NAME_CONTRACT_STATUS               0
CNT_DRAWINGS_CURRENT               0
AMT_PAYMENT_TOTAL_CURRENT          0
AMT_RECIVABLE                      0
AMT_RECEIVABLE_PRINCIPAL           0
SK_ID_CURR                         0
AMT_DRAWINGS_CURRENT               0
AMT_CREDIT_LIMIT_ACTUAL            0
AMT_BALANCE                        0
MONTHS_BALANCE                     0
SK_DPD_DEF                         0
dtype: int64

In [82]:
credit_card_balance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3840312 entries, 0 to 3840311
Data columns (total 23 columns):
 #   Column                      Dtype
---  ------                      -----
 0   SK_ID_PREV                  int64
 1   SK_ID_CURR                  int64
 2   MONTHS_BALANCE              int64
 3   AMT_BALANCE                 float64
 4   AMT_CREDIT_LIMIT_ACTUAL     int64
 5   AMT_DRAWINGS_ATM_CURRENT    float64
 6   AMT_DRAWINGS_CURRENT        float64
 7   AMT_DRAWINGS_OTHER_CURRENT  float64
 8   AMT_DRAWINGS_POS_CURRENT    float64
 9   AMT_INST_MIN_REGULARITY     float64
 10  AMT_PAYMENT_CURRENT         float64
 11  AMT_PAYMENT_TOTAL_CURRENT   float64
 12  AMT_RECEIVABLE_PRINCIPAL    float64
 13  AMT_RECIVABLE               float64
 14  AMT_TOTAL_RECEIVABLE        float64
 15  CNT_DRAWINGS_ATM_CURRENT    float64
 16  CNT_DRAWINGS_CURRENT        int64
 17  CNT_DRAWINGS_OTHER_CURRENT  float64
 18  CNT_DRAWINGS_POS_CURRENT    float64
 19  CNT_INSTALMENT_MATURE_CUM   float64
 20  NAME_CONTRACT_STATUS        object
 21  SK_DPD                      int64
 22  SK_DPD_DEF                  int64
dtypes: float64(15), int64(7), object(1)
memory usage: 673.9+ MB

In [83]:
credit_card_balance["utilization_rate"] = (
    credit_card_balance["AMT_BALANCE"] /
    (credit_card_balance["AMT_CREDIT_LIMIT_ACTUAL"] + 1)
)
#negative Werte möglich

In [85]:
credit_card_balance[credit_card_balance["AMT_BALANCE"] < 0].head(20)

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,utilization_rate
17248,1249602,446446,-43,-428.040,45000,0.0,0.0,0.0,0.0,0.000,...,-428.040,0.0,0,0.0,0.0,17.0,Active,0,0,-0.009512
17250,1390845,198928,-45,-395.055,180000,0.0,0.0,0.0,0.0,0.000,...,-395.055,0.0,0,0.0,0.0,5.0,Active,0,0,-0.002195
17256,1592788,142772,-47,-220.635,135000,0.0,0.0,0.0,0.0,0.000,...,-220.635,0.0,0,0.0,0.0,11.0,Active,0,0,-0.001634
17267,1837275,349932,-41,-399.645,45000,0.0,0.0,0.0,0.0,0.000,...,-399.645,0.0,0,0.0,0.0,3.0,Active,0,0,-0.008881
17303,1030390,187102,-44,-135359.010,180000,0.0,0.0,0.0,0.0,12600.000,...,-133442.235,0.0,0,0.0,0.0,7.0,Active,0,0,-0.751990
17309,1406356,172393,-47,-64.170,90000,0.0,0.0,0.0,0.0,96.255,...,3.330,0.0,0,0.0,0.0,23.0,Active,0,0,-0.000713
17486,2088679,114914,-43,-116.460,90000,0.0,0.0,0.0,0.0,0.000,...,-116.460,0.0,0,0.0,0.0,13.0,Active,0,0,-0.001294
17489,1568713,267079,-51,-1360.080,90000,0.0,0.0,0.0,0.0,386.370,...,-1292.580,0.0,0,0.0,0.0,3.0,Active,0,0,-0.015112
17521,1232457,450229,-51,-650.295,270000,0.0,0.0,0.0,0.0,0.000,...,-650.295,0.0,0,0.0,0.0,17.0,Active,0,0,-0.002408
17687,1716521,135424,-45,-310.095,427500,0.0,0.0,0.0,0.0,384.885,...,-242.595,0.0,0,0.0,0.0,3.0,Active,0,0,-0.000725
17693,1313453,155388,-41,-6757.200,180000,0.0,0.0,0.0,0.0,323.865,...,-6689.700,0.0,0,0.0,0.0,18.0,Active,0,0,-0.037540
22493,1194407,139583,-46,-874.035,90000,0.0,0.0,0.0,0.0,0.000,...,-874.035,0.0,0,0.0,0.0,2.0,Active,0,0,-0.009711
22502,1515659,203925,-48,-228.690,45000,0.0,0.0,0.0,0.0,0.000,...,-228.690,0.0,0,0.0,0.0,5.0,Active,0,0,-0.005082
22520,1056440,265327,-44,-1895.760,225000,0.0,0.0,0.0,0.0,0.000,...,-1895.760,0.0,0,0.0,0.0,9.0,Active,0,0,-0.008426
22556,1165173,381968,-49,-808.515,67500,0.0,0.0,0.0,0.0,0.000,...,-808.515,0.0,0,0.0,0.0,6.0,Active,0,0,-0.011978
22570,1922872,296228,-41,-13275.000,90000,NaN,0.0,NaN,NaN,NaN,...,-13275.000,NaN,0,NaN,NaN,NaN,Active,0,0,-0.147498
22605,2618302,325207,-41,-386.010,67500,0.0,0.0,0.0,0.0,0.000,...,-386.010,0.0,0,0.0,0.0,3.0,Active,0,0,-0.005719
22797,1926622,158952,-50,-99.315,180000,0.0,0.0,0.0,0.0,0.000,...,-99.315,0.0,0,0.0,0.0,13.0,Active,0,0,-0.000552
22835,1060391,436533,-46,-144.540,45000,0.0,0.0,0.0,0.0,0.000,...,-144.540,0.0,0,0.0,0.0,8.0,Active,0,0,-0.003212
22884,2707110,427698,-41,-7895.250,90000,0.0,0.0,0.0,0.0,94.365,...,-7895.250,0.0,0,0.0,0.0,9.0,Active,0,0,-0.087724

In [86]:
cc_agg = credit_card_balance.groupby("SK_ID_CURR").agg(
    cc_prev_loans=("SK_ID_PREV", "nunique"),
    cc_avg_payment=("AMT_PAYMENT_TOTAL_CURRENT", "mean"),
    cc_total_payment=("AMT_PAYMENT_TOTAL_CURRENT", "sum"),
    cc_avg_balance=("AMT_BALANCE", "mean"),
    cc_max_balance=("AMT_BALANCE", "max"),
    cc_avg_utilization=("utilization_rate", "mean"),
    cc_max_utilization=("utilization_rate", "max"),
    cc_installments_mature=("CNT_INSTALMENT_MATURE_CUM", "max"),
    cc_max_dpd=("SK_DPD_DEF", "max"),
    cc_bad_months=("SK_DPD_DEF", lambda x: (x > 0).sum()),
)

application_train = application_train.merge(cc_agg, on="SK_ID_CURR", how="left")

In [ ]:
#installments_payments

In [88]:
installments_payments.shape

(13605401, 8)